data = [
    {"text": "<s>[INST] What is Nuflorist? [/INST] Nuflorist provides the perfect tools to maximize efficiency and revenue, addressing all the needs of running a floral business on Shopify. Create occasions for upselling products, enhance user experience with customizable app widgets for product pages, and customize shipping rates and zones with time and date checkout blocks </s>"},
    {"text": "<s>[INST] What is the Product Widget? [/INST] The product page widget in NuFlorist is a customizable widget that integrates with your Shopify store to display occasions and add-ons to your customers. </s>"},
    {"text": "<s>[INST] What is the Cart Widget? [/INST] The Cart Theme Extension seamlessly integrates with your Shopify store, enhancing the checkout experience for customers. </s>"},
    {"text": "<s>[INST] How many messages can I add to each occasion? [/INST] You can add up to 10 messages to each occasion. This allows you to provide a variety of pre-set messages for different occasions. </s>"},
    {"text": "<s>[INST] What is an occasion? [/INST] Occasions are pre-configured settings that allow you to customize the shopping experience for specific events or themes. </s>"},
    {"text": "<s>[INST] How can I feature the widget in my Shopify store? [/INST] To feature the widget in your Shopify store, you need to enable the app block on your product page. Go to your theme editor, find the app block inside the product page, and add it to your product template.  </s>"},
    {"text": "<s>[INST] What Requirements do i need to use the delivery feature? [/INST] Your shopify store needs to either have the advance plane, being in a yearly billed in any plan or lastly pay on a montly basis for a custom carrier service  </s>"},
    {"text": "<s>[INST] How can I delete addons categories? [/INST] Navigate to the section where your addons categories are listed, You will see a button at the bottom of the page called “Delete category”  </s>"},
    {"text": "<s>[INST] How can I create addons categories? [/INST] You can create an addons category by accessing the Add-on section under your Nuflorist App and following the step-by-step tutorial. </s>"},
    {"text": "<s>[INST] Where are you located? [/INST] We are based in Miami. </s>"},
    {"text": "<s>[INST] What flowers do you sell? [/INST] We sell roses, tulips, and daisies. </s>"},
    {"text": "<s>[INST] Do you have same-day delivery? [/INST] Yes, in selected locations. </s>"},
    {"text": "<s>[INST] Can I order a custom bouquet? [/INST] Yes, we specialize in custom arrangements. </s>"},
    {"text": "<s>[INST] Do you deliver to Chicago? [/INST] No, we deliver to Miami and nearby areas. </s>"},
    {"text": "<s>[INST] Where do you work? [/INST] Nuflorist. </s>"},
    {"text": "<s>[INST] What types of bouquets do you offer? [/INST] We offer a range of bouquets including roses, lilies, and seasonal mixes tailored for every occasion. </s>"},
    {"text": "<s>[INST] How do I care for my roses? [/INST] Roses thrive with regular watering, proper sunlight, and occasional fertilization. We recommend trimming dead blooms regularly. </s>"},
    {"text": "<s>[INST] Do you offer same-day delivery? [/INST] Yes, we offer same-day delivery in select areas. Please provide your zip code for availability. </s>"},
    {"text": "<s>[INST] Can I request a custom floral arrangement for a wedding? [/INST] Absolutely. We specialize in custom designs. Let's discuss your vision and requirements in detail. </s>"},
    {"text": "<s>[INST] What flowers are in season right now? [/INST] Currently, seasonal options include tulips, daffodils, and peonies. They’re perfect for adding a vibrant touch to any setting. </s>"},
    {"text": "<s>[INST] What do lilies symbolize? [/INST] Lilies often symbolize purity and refined beauty, making them a popular choice for celebratory events. </s>"},
    {"text": "<s>[INST] Do you provide floral arrangements for birthdays? [/INST] Yes, we create vibrant arrangements perfect for celebrating birthdays. </s>"},
    {"text": "<s>[INST] What types of flowers are good for anniversaries? [/INST] Roses and lilies are popular choices for anniversaries, symbolizing love and commitment. </s>"},
    {"text": "<s>[INST] Can I include a personalized note with my bouquet? [/INST] Absolutely. You can include a personalized message with every bouquet. </s>"},
    {"text": "<s>[INST] Do you offer gift-wrapping services? [/INST] Yes, all our bouquets come with elegant gift wrapping. </s>"},
    {"text": "<s>[INST] What add-ons can I include with my bouquet? [/INST] You can include chocolates, balloons, or teddy bears as add-ons with your bouquet. </s>"},
    {"text": "<s>[INST] Do you offer corporate flower arrangements? [/INST] Yes, we provide custom arrangements for corporate events and offices. </s>"},
    {"text": "<s>[INST] Can I schedule a delivery for a specific date? [/INST] Yes, you can schedule deliveries for any specific date. </s>"},
    {"text": "<s>[INST] Do you offer sympathy or funeral flower arrangements? [/INST] Yes, we offer arrangements specifically designed for sympathy and funerals. </s>"},
    {"text": "<s>[INST] What flowers do you recommend for Valentine’s Day? [/INST] Roses are our top recommendation for Valentine’s Day, but we also offer tulips and mixed bouquets. </s>"},
    {"text": "<s>[INST] Do you provide floral centerpieces for events? [/INST] Yes, we specialize in creating floral centerpieces for weddings, parties, and corporate events. </s>"},
    {"text": "<s>[INST] Can I order flowers for same-day delivery on weekends? [/INST] Yes, same-day delivery is available on weekends in select areas. </s>"},
    {"text": "<s>[INST] Do you offer flowers for holidays like Mother’s Day? [/INST] Yes, we offer special bouquets for holidays like Mother’s Day and Christmas. </s>"},
    {"text": "<s>[INST] Can I cancel or modify my order? [/INST] Yes, you can cancel or modify your order if done within 24 hours of placing it. </s>"},
    {"text": "<s>[INST] Do you offer discounts for bulk orders? [/INST] Yes, we provide discounts for bulk orders. Please contact us for more details. </s>"},
    {"text": "<s>[INST] What are your delivery hours? [/INST] We deliver from 8 AM to 8 PM, seven days a week. </s>"},
    {"text": "<s>[INST] Can I track my flower delivery? [/INST] Yes, you’ll receive a tracking link once your order is dispatched. </s>"},
    {"text": "<s>[INST] Do you deliver flowers internationally? [/INST] Currently, we only deliver within Miami and nearby areas. </s>"},
    {"text": "<s>[INST] What payment methods do you accept? [/INST] We accept credit cards, PayPal, and major digital wallets. </s>"},
    {"text": "<s>[INST] How do I get in touch with customer service? [/INST] You can contact us via email or phone during business hours. </s>"},
    {"text": "<s>[INST] Hello, I need help with my order. [/INST] Sure, please provide your order details, and we'll assist you right away. </s>"},
    {"text": "<s>[INST] Can I get a refund for a damaged order? [/INST] Yes, please provide a photo of the damaged order, and we'll process a refund or replacement. </s>"},
    {"text": "<s>[INST] How much does same-day delivery cost? [/INST] Same-day delivery costs vary by location. Please check during checkout. </s>"},
    {"text": "<s>[INST] What should I do if my flowers didn’t arrive on time? [/INST] Contact us immediately so we can track your delivery and resolve the issue. </s>"},
    {"text": "<s>[INST] What is your return policy? [/INST] We accept returns for damaged or incorrect orders within 48 hours of delivery. </s>"},
    {"text": "<s>[INST] Do you offer seasonal flower subscriptions? [/INST] Yes, we offer monthly or seasonal flower subscription plans. </s>"},
    {"text": "<s>[INST] How do I track my flower delivery? [/INST] A tracking link will be sent to you once your flowers are dispatched. </s>"},
    {"text": "<s>[INST] Can I order flowers by phone? [/INST] Yes, our customer service team can assist with phone orders during business hours. </s>"},
    {"text": "<s>[INST] Are your flowers eco-friendly? [/INST] Yes, we prioritize sustainably sourced flowers in all our arrangements. </s>"},
    {"text": "<s>[INST] Do you sell flowers in bulk for events? [/INST] Yes, we offer bulk flowers for weddings and events at discounted rates. </s>"},
    {"text": "<s>[INST] Can I pay with PayPal? [/INST] Yes, we accept PayPal along with credit cards and digital wallets. </s>"},
    {"text": "<s>[INST] What if I’m not happy with my order? [/INST] Please reach out to us, and we'll work to resolve any issues promptly. </s>"},
    {"text": "<s>[INST] How do I make sure my flowers last longer? [/INST] Change the water every 2 days and trim the stems regularly. </s>"},
    {"text": "<s>[INST] What are your customer support hours? [/INST] Our support team is available from 8 AM to 8 PM daily. </s>"},
    {"text": "<s>[INST] Can I request a specific delivery time? [/INST] Yes, you can specify a delivery time during checkout. </s>"},
    {"text": "<s>[INST] Do you offer flowers for graduation? [/INST] Yes, we have bouquets designed especially for graduations. </s>"},
    {"text": "<s>[INST] Are your arrangements customizable? [/INST] Yes, we can customize arrangements to suit your preferences. </s>"},
    {"text": "<s>[INST] How can I enhance my flower shop’s sales with Nuflorist? [/INST] Nuflorist helps you boost sales with add-on suggestions, customizable widgets, and occasion-based upselling strategies tailored to your Shopify store. </s>"},
    {"text": "<s>[INST] What occasions can I set up in Nuflorist? [/INST] You can set up occasions like birthdays, anniversaries, weddings, or any custom event to upsell products effectively. </s>"},
    {"text": "<s>[INST] Can Nuflorist help me manage add-ons for bouquets? [/INST] Absolutely! Nuflorist allows you to link add-ons like chocolates, balloons, or vases to specific products for seamless upselling. </s>"},
    {"text": "<s>[INST] Does Nuflorist support custom messages for bouquets? [/INST] Yes, you can create personalized message suggestions for any occasion, making it easier for customers to add a thoughtful touch. </s>"},
    {"text": "<s>[INST] What are app blocks in Nuflorist? [/INST] App blocks are customizable widgets like product page blocks, announcement bars, and zipcode verifiers designed to enhance customer experience and revenue. </s>"},
    {"text": "<s>[INST] How does Nuflorist help with delivery logistics? [/INST] Nuflorist allows you to customize shipping rates, set padding times, enable same-day delivery rules, and block out busy holiday dates. </s>"},
    {"text": "<s>[INST] Can I schedule delivery dates for my customers using Nuflorist? [/INST] Yes, Nuflorist includes a date and time picker at checkout, allowing customers to choose their preferred delivery schedule. </s>"},
    {"text": "<s>[INST] How does Nuflorist handle busy holiday deliveries? [/INST] You can set flexible delivery rates, apply discounts, or block specific dates during high-demand periods like Valentine’s Day or Mother’s Day. </s>"},
    {"text": "<s>[INST] Does Nuflorist work with Shopify Plus? [/INST] Yes, Nuflorist integrates seamlessly with Shopify Plus, offering advanced features like time and date delivery pickers. </s>"},
    {"text": "<s>[INST] How do I use Nuflorist to recommend add-ons for an anniversary bouquet? [/INST] Nuflorist connects add-ons like chocolates or candles to anniversary bouquets, increasing the average order value with personalized recommendations. </s>"},
    {"text": "<s>[INST] What is the zipcode verifier in Nuflorist? [/INST] The zipcode verifier lets customers check delivery availability before placing an order, improving user experience and order accuracy. </s>"},
    {"text": "<s>[INST] Can Nuflorist help with upselling during checkout? [/INST] Yes, Nuflorist’s app blocks and add-on recommendations are designed to enhance upselling opportunities directly in the checkout flow. </s>"},
    {"text": "<s>[INST] Is Nuflorist suitable for managing wedding flower orders? [/INST] Definitely! Nuflorist allows you to create custom arrangements, manage delivery schedules, and offer occasion-specific add-ons for weddings. </s>"},
    {"text": "<s>[INST] What tools does Nuflorist offer for customer engagement? [/INST] Nuflorist provides features like personalized message suggestions, app blocks for product pages, and occasion-based upselling strategies to boost engagement. </s>"},
    {"text": "<s>[INST] How do I block specific delivery dates using Nuflorist? [/INST] You can block dates directly in the Nuflorist settings, ensuring no orders are scheduled for unavailable days. </s>"},
    {"text": "<s>[INST] Can Nuflorist improve my store’s checkout process? [/INST] Yes, Nuflorist offers a delivery date and time picker, flexible shipping rules, and add-on suggestions to enhance the checkout experience. </s>"},
    {"text": "<s>[INST] How do I set up a holiday promotion with Nuflorist? [/INST] You can use Nuflorist to create special holiday-themed add-ons, offer delivery discounts, and showcase promotional banners through app blocks. </s>"},
    {"text": "<s>[INST] Does Nuflorist support same-day delivery? [/INST] Yes, Nuflorist allows you to configure same-day delivery rules based on location and order time. </s>"},
    {"text": "<s>[INST] Can Nuflorist help me customize product pages for occasions? [/INST] Absolutely! Nuflorist’s app blocks let you tailor product pages with occasion selectors, add-ons, and message options. </s>"},
    {"text": "<s>[INST] How do I contact Nuflorist for support? [/INST] You can reach us at info@nuflorist.com or call 844-682-5666 for any assistance. </s>"},
    {"text": "<s>[INST] Does Nuflorist help me track delivery efficiency? [/INST] While Nuflorist focuses on setup and customization, Shopify’s tracking features can be integrated for monitoring deliveries. </s>"},
    {"text": "<s>[INST] What kind of add-ons can I link to products using Nuflorist? [/INST] You can link add-ons like greeting cards, chocolates, balloons, or even subscription services to boost sales. </s>"},
    {"text": "<s>[INST] Can I customize delivery rates by location with Nuflorist? [/INST] Yes, Nuflorist allows you to set delivery rates based on zipcodes, distance, and other location-specific rules. </s>"},
    {"text": "<s>[INST] How do I start using Nuflorist? [/INST] Simply install the app from the Shopify App Store, configure your settings, and explore its features for managing occasions, add-ons, and delivery rules. </s>"},
    {"text": "<s>[INST] Who is Danny Sanchez, and what role does he play at NuFlorist? [/INST] Danny Sanchez is the CEO and founder of NuFlorist, leveraging his expertise as a seasoned florist to develop innovative solutions for floral businesses. </s>"},
    {"text": "<s>[INST] How does Danny Sanchez’s experience influence NuFlorist’s solutions? [/INST] His background as a florist enables him to address industry-specific challenges, creating tailored tools for e-commerce success. </s>"},
    {"text": "<s>[INST] What is NuFlorist’s mission under Danny Sanchez’s leadership? [/INST] NuFlorist aims to empower florists with modern technology, enhancing efficiency, customer engagement, and revenue generation. </s>"},
    {"text": "<s>[INST] How does NuFlorist bridge the gap between traditional floristry and e-commerce? [/INST] NuFlorist provides tools like customizable product listings, seamless order management, and delivery scheduling to modernize floral businesses. </s>"},
    {"text": "<s>[INST] Why is the Florist Shopify App a significant milestone for NuFlorist? [/INST] The app revolutionizes online floral businesses with tailored solutions for florists, streamlining operations and boosting online engagement. </s>"},
    {"text": "<s>[INST] What features does NuFlorist’s app offer to enhance order management? [/INST] The app automates order processing, organizes workflows, and allows for customizable delivery scheduling. </s>"},
    {"text": "<s>[INST] How can florists increase their online presence with NuFlorist’s tools? [/INST] By leveraging Shopify’s infrastructure, florists can create engaging product listings and improve customer interactions. </s>"},
    {"text": "<s>[INST] What tools does NuFlorist provide to eliminate waste and increase productivity? [/INST] NuFlorist offers solutions that streamline operations, including efficient administrative, marketing, and communication tools. </s>"},
    {"text": "<s>[INST] How does NuFlorist handle delivery customization for busy holidays? [/INST] The app allows for flexible delivery discounts, blocked dates, and customized shipping rates to accommodate peak seasons. </s>"},
    {"text": "<s>[INST] Where can I learn more about NuFlorist or get support? [/INST] You can visit https://nuflorist.com, email info@nuflorist.com, or call 844-682-5666 for assistance. </s>"},
    {"text": "<s>[INST] How does the Florist Shopify App help florists boost customer engagement? [/INST] The app includes features like delivery date pickers and occasion-based add-on recommendations to improve the shopping experience. </s>"},
    {"text": "<s>[INST] What are the benefits of NuFlorist’s delivery picker tool? [/INST] The delivery picker allows customers to choose specific delivery dates and times, enhancing flexibility and customer satisfaction. </s>"},
    {"text": "<s>[INST] Why did Danny Sanchez develop the Florist Shopify App? [/INST] He recognized a gap in the market for e-commerce solutions tailored specifically for florists and created the app to fill that need. </s>"},
    {"text": "<s>[INST] How does NuFlorist address the challenges of running an online floral business? [/INST] NuFlorist provides customizable tools for product listings, order management, and delivery scheduling, tailored to the needs of florists. </s>"},
    {"text": "<s>[INST] What is NuFlorist’s approach to sustainable floristry? [/INST] NuFlorist’s tools optimize operations to reduce resource waste, supporting both sustainability and profitability. </s>"},
    {"text": "<s>[INST] How does NuFlorist use Shopify to enhance florists’ e-commerce operations? [/INST] NuFlorist integrates seamlessly with Shopify to offer robust e-commerce tools like customizable widgets and delivery scheduling. </s>"},
    {"text": "<s>[INST] What customer engagement features does NuFlorist offer for florists? [/INST] NuFlorist enhances customer experience with add-on suggestions, occasion-based upselling, and flexible delivery options. </s>"},
    {"text": "<s>[INST] How does NuFlorist support florists during peak seasons? [/INST] The app provides tools for flexible delivery rates, blocked dates, and discounts to efficiently manage high demand. </s>"},
    {"text": "<s>[INST] What is Danny Sanchez’s vision for NuFlorist? [/INST] He aims to empower florists with tools to thrive in the competitive e-commerce space while modernizing traditional practices. </s>"},
    {"text": "<s>[INST] What makes NuFlorist unique in the floral industry? [/INST] NuFlorist combines floristry expertise and cutting-edge technology to offer solutions specifically tailored to floral businesses. </s>"},
    {"text": "<s>[INST] What inspired Danny Sanchez to develop solutions for the challenges florists face? [/INST] Danny’s experience with South Florals Group and his tech background drove him to create tools that address industry-specific issues. </s>"},
    {"text": "<s>[INST] What are the main challenges flower shop owners face, according to Danny Sanchez? [/INST] Challenges include managing perishable inventory, intense competition, rising costs, and effective marketing and customer engagement. </s>"},
    {"text": "<s>[INST] How does NuFlorist help florists with inventory management? [/INST] NuFlorist offers tools like iFlorist, which includes scheduling, projections, and inventory control to minimize waste and maximize profitability. </s>"},
    {"text": "<s>[INST] Why are perishability and inventory management significant challenges in the floral business? [/INST] Flowers are highly perishable, requiring precise inventory management to avoid waste or stockouts, which can lead to financial losses or dissatisfied customers. </s>"},
    {"text": "<s>[INST] How has competition impacted traditional brick-and-mortar flower shops? [/INST] Intense competition from online retailers and chain stores forces florists to adapt pricing strategies and innovate to maintain profitability. </s>"},
    {"text": "<s>[INST] What operational costs do flower shop owners struggle with, as highlighted by Danny Sanchez? [/INST] Costs include sourcing flowers, rent, utilities, labor, fuel price fluctuations, and currency exchange rates, which can impact margins. </s>"},
    {"text": "<s>[INST] How can flower shops improve their marketing and customer engagement? [/INST] By building a strong online presence through social media, email marketing, and visually appealing websites to attract customers and cultivate loyalty. </s>"},
    {"text": "<s>[INST] What is BloomView, and how does it benefit florists? [/INST] BloomView is a photo-sharing app that helps florists gather feedback and reviews from customers, enhancing engagement and boosting online sales. </s>"},
    {"text": "<s>[INST] What are the key features of the iFlorist management suite? [/INST] iFlorist includes tools for scheduling, cost management, projections, and inventory control to streamline floral business operations. </s>"},
    {"text": "<s>[INST] Why does Danny Sanchez believe technology is essential for the floral business? [/INST] Technology can address unique challenges florists face, such as inventory management, competition, and customer engagement, by providing tailored solutions. </s>"},
    {"text": "<s>[INST] How does NuFlorist address the lack of floral business-centric tools? [/INST] NuFlorist provides innovative solutions like BloomView and iFlorist, designed specifically to meet the needs of florists. </s>"},
    {"text": "<s>[INST] What lessons did Danny Sanchez learn from South Florals Group that influenced NuFlorist? [/INST] He learned the importance of addressing perishability, competition, and rising costs with tailored, tech-driven solutions. </s>"},
    {"text": "<s>[INST] What recognition has Danny Sanchez received for his contributions to the floral industry? [/INST] Danny earned a spot on SFBJ’s 40 under 40 in 2022 for his achievements with South Florals Group and contributions to the industry. </s>"},
    {"text": "<s>[INST] How does the floral industry differ from other retail sectors? [/INST] Flowers are highly perishable, requiring unique inventory management strategies, and the industry faces intense competition and pricing pressures. </s>"},
    {"text": "<s>[INST] How does BloomView encourage customer engagement and reviews? [/INST] The app sends customers a photo of their order and guides them through the review process, enhancing satisfaction and online presence. </s>"},
    {"text": "<s>[INST] What role does customer satisfaction play in the floral business’s success? [/INST] Prioritizing customer satisfaction helps florists build loyalty, attract new customers, and stand out in a competitive marketplace. </s>"},
    {"text": "<s>[INST] How is the floral industry expected to evolve with tools like NuFlorist? [/INST] NuFlorist’s tailored solutions aim to modernize operations, reduce traditional challenges, and create more opportunities for growth and efficiency. </s>"},
    {"text": "<s>[INST] Why is the iFlorist suite launching important for floral businesses? [/INST] The suite offers essential tools for managing costs, inventory, and labor, helping florists optimize their operations and profitability. </s>"},
    {"text": "<s>[INST] How do rising costs impact the profitability of flower shops? [/INST] Increased expenses for sourcing, utilities, and imported flowers reduce profit margins, requiring florists to adopt innovative strategies. </s>"},
    {"text": "<s>[INST] What strategies can florists use to remain competitive in a crowded marketplace? [/INST] Florists can adopt technology like NuFlorist’s tools, improve online marketing, and optimize inventory management to stay competitive. </s>"},
    {"text": "<s>[INST] Who is Danny Sanches? [/INST] Danny Sanches is a professional florist specializing in custom arrangements. </s>"},
    {"text": "<s>[INST] What bouquets are available? [/INST] We offer roses, lilies, and seasonal mixes for all occasions. </s>"},
    {"text": "<s>[INST] How to care for roses? [/INST] Water them, provide sunlight, and trim dead blooms. </s>"},
    {"text": "<s>[INST] Do you have same-day delivery? [/INST] Yes, same-day delivery is available in select areas. </s>"},
    {"text": "<s>[INST] Can I request custom wedding flowers? [/INST] Absolutely! Let’s discuss your vision in detail. </s>"},
    {"text": "<s>[INST] What flowers are in season? [/INST] Tulips, daffodils, and peonies are currently in season. </s>"},
    {"text": "<s>[INST] What do lilies symbolize? [/INST] Lilies symbolize purity and refined beauty. </s>"},
    {"text": "<s>[INST] Do you create birthday bouquets? [/INST] Yes, we design vibrant arrangements for birthdays. </s>"},
    {"text": "<s>[INST] What flowers suit anniversaries? [/INST] Roses and lilies are popular for anniversaries. </s>"},
    {"text": "<s>[INST] Can I add a note to my bouquet? [/INST] Yes, personalized notes are included with every bouquet. </s>"},
    {"text": "<s>[INST] Do you offer gift wrapping? [/INST] Yes, all bouquets come with elegant gift wrapping. </s>"},
    {"text": "<s>[INST] What add-ons can I include? [/INST] Add-ons include chocolates, balloons, and teddy bears. </s>"},
    {"text": "<s>[INST] Do you provide corporate arrangements? [/INST] Yes, we create custom arrangements for offices and events. </s>"},
    {"text": "<s>[INST] Can I schedule a delivery? [/INST] Yes, you can pick a specific delivery date. </s>"},
    {"text": "<s>[INST] Do you have sympathy flowers? [/INST] Yes, we design flowers for sympathy and funerals. </s>"},
    {"text": "<s>[INST] What flowers are best for Valentine’s Day? [/INST] Roses are top picks, but tulips and mixed bouquets are available too. </s>"},
    {"text": "<s>[INST] Do you offer event centerpieces? [/INST] Yes, we create centerpieces for weddings, parties, and more. </s>"},
    {"text": "<s>[INST] Is same-day delivery available on weekends? [/INST] Yes, in select areas. </s>"},
    {"text": "<s>[INST] Do you have holiday bouquets? [/INST] Yes, we offer special bouquets for Mother’s Day and Christmas. </s>"},
    {"text": "<s>[INST] Can I cancel or change my order? [/INST] Yes, within 24 hours of placing it. </s>"},
    {"text": "<s>[INST] Do you offer discounts for bulk orders? [/INST] Yes, contact us for more details. </s>"},
    {"text": "<s>[INST] What are your delivery hours? [/INST] We deliver from 8 AM to 8 PM daily. </s>"},
    {"text": "<s>[INST] Can I track my order? [/INST] Yes, you’ll receive a tracking link. </s>"},
    {"text": "<s>[INST] Do you deliver internationally? [/INST] No, we currently deliver only in Miami. </s>"},
    {"text": "<s>[INST] What payment methods are accepted? [/INST] We accept cards, PayPal, and digital wallets. </s>"},
    {"text": "<s>[INST] How can I contact customer service? [/INST] Email or call us during business hours. </s>"},
    {"text": "<s>[INST] Can I get a refund for damaged flowers? [/INST] Yes, provide a photo, and we’ll replace or refund. </s>"},
    {"text": "<s>[INST] What is same-day delivery cost? [/INST] Costs vary by location; check at checkout. </s>"},
    {"text": "<s>[INST] What if my flowers are late? [/INST] Contact us to resolve any delays. </s>"},
    {"text": "<s>[INST] What is your return policy? [/INST] Returns are accepted for damaged orders within 48 hours. </s>"},
    {"text": "<s>[INST] Do you have flower subscriptions? [/INST] Yes, we offer monthly and seasonal plans. </s>"},
    {"text": "<s>[INST] Can I order by phone? [/INST] Yes, call us during business hours. </s>"},
    {"text": "<s>[INST] Are your flowers eco-friendly? [/INST] Yes, we prioritize sustainable sourcing. </s>"},
    {"text": "<s>[INST] Do you sell bulk flowers? [/INST] Yes, for weddings and events. </s>"},
    {"text": "<s>[INST] Can I pay with PayPal? [/INST] Yes, PayPal is accepted. </s>"},
    {"text": "<s>[INST] What if I’m unhappy with my order? [/INST] Contact us to resolve any issues. </s>"},
    {"text": "<s>[INST] How to keep flowers fresh? [/INST] Change water, trim stems, and avoid direct sunlight. </s>"},
    {"text": "<s>[INST] What are customer support hours? [/INST] Support is available 8 AM to 8 PM daily. </s>"},
    {"text": "<s>[INST] Can I choose a delivery time? [/INST] Yes, specify at checkout. </s>"},
    {"text": "<s>[INST] Do you offer graduation flowers? [/INST] Yes, we have bouquets for graduations. </s>"},
    {"text": "<s>[INST] Are arrangements customizable? [/INST] Yes, we customize to suit your needs. </s>"}
]

