data = [
    {"text": "<s>[INST] Where are you located? [/INST] We are based in Miami. </s>"},
    {"text": "<s>[INST] What flowers do you sell? [/INST] We sell roses, tulips, and daisies. </s>"},
    {"text": "<s>[INST] Do you have same-day delivery? [/INST] Yes, in selected locations. </s>"},
    {"text": "<s>[INST] Can I order a custom bouquet? [/INST] Yes, we specialize in custom arrangements. </s>"},
    {"text": "<s>[INST] Do you deliver to Chicago? [/INST] No, we deliver to Miami and nearby areas. </s>"},
    {"text": "<s>[INST] Where do you work? [/INST] Nuflorist. </s>"},
    {"text": "<s>[INST] What types of bouquets do you offer? [/INST] We offer a range of bouquets including roses, lilies, and seasonal mixes tailored for every occasion. </s>"},
    {"text": "<s>[INST] How do I care for my roses? [/INST] Roses thrive with regular watering, proper sunlight, and occasional fertilization. We recommend trimming dead blooms regularly. </s>"},
    {"text": "<s>[INST] Do you offer same-day delivery? [/INST] Yes, we offer same-day delivery in select areas. Please provide your zip code for availability. </s>"},
    {"text": "<s>[INST] Can I request a custom floral arrangement for a wedding? [/INST] Absolutely. We specialize in custom designs. Let's discuss your vision and requirements in detail. </s>"},
    {"text": "<s>[INST] What flowers are in season right now? [/INST] Currently, seasonal options include tulips, daffodils, and peonies. They’re perfect for adding a vibrant touch to any setting. </s>"},
    {"text": "<s>[INST] What do lilies symbolize? [/INST] Lilies often symbolize purity and refined beauty, making them a popular choice for celebratory events. </s>"},
    {"text": "<s>[INST] Do you provide floral arrangements for birthdays? [/INST] Yes, we create vibrant arrangements perfect for celebrating birthdays. </s>"},
    {"text": "<s>[INST] What types of flowers are good for anniversaries? [/INST] Roses and lilies are popular choices for anniversaries, symbolizing love and commitment. </s>"},
    {"text": "<s>[INST] Can I include a personalized note with my bouquet? [/INST] Absolutely. You can include a personalized message with every bouquet. </s>"},
    {"text": "<s>[INST] Do you offer gift-wrapping services? [/INST] Yes, all our bouquets come with elegant gift wrapping. </s>"},
    {"text": "<s>[INST] What add-ons can I include with my bouquet? [/INST] You can include chocolates, balloons, or teddy bears as add-ons with your bouquet. </s>"},
    {"text": "<s>[INST] Do you offer corporate flower arrangements? [/INST] Yes, we provide custom arrangements for corporate events and offices. </s>"},
    {"text": "<s>[INST] Can I schedule a delivery for a specific date? [/INST] Yes, you can schedule deliveries for any specific date. </s>"},
    {"text": "<s>[INST] Do you offer sympathy or funeral flower arrangements? [/INST] Yes, we offer arrangements specifically designed for sympathy and funerals. </s>"},
    {"text": "<s>[INST] What flowers do you recommend for Valentine’s Day? [/INST] Roses are our top recommendation for Valentine’s Day, but we also offer tulips and mixed bouquets. </s>"},
    {"text": "<s>[INST] Do you provide floral centerpieces for events? [/INST] Yes, we specialize in creating floral centerpieces for weddings, parties, and corporate events. </s>"},
    {"text": "<s>[INST] Can I order flowers for same-day delivery on weekends? [/INST] Yes, same-day delivery is available on weekends in select areas. </s>"},
    {"text": "<s>[INST] Do you offer flowers for holidays like Mother’s Day? [/INST] Yes, we offer special bouquets for holidays like Mother’s Day and Christmas. </s>"},
    {"text": "<s>[INST] Can I cancel or modify my order? [/INST] Yes, you can cancel or modify your order if done within 24 hours of placing it. </s>"},
    {"text": "<s>[INST] Do you offer discounts for bulk orders? [/INST] Yes, we provide discounts for bulk orders. Please contact us for more details. </s>"},
    {"text": "<s>[INST] What are your delivery hours? [/INST] We deliver from 8 AM to 8 PM, seven days a week. </s>"},
    {"text": "<s>[INST] Can I track my flower delivery? [/INST] Yes, you’ll receive a tracking link once your order is dispatched. </s>"},
    {"text": "<s>[INST] Do you deliver flowers internationally? [/INST] Currently, we only deliver within Miami and nearby areas. </s>"},
    {"text": "<s>[INST] What payment methods do you accept? [/INST] We accept credit cards, PayPal, and major digital wallets. </s>"},
]
