data = [
    {"text": "<s>[INST] What products do you sell? [/INST] We offer a wide variety of electronics including smartphones, laptops, tablets, televisions, cameras, and home appliances. </s>"},
    {"text": "<s>[INST] Do you offer product warranties? [/INST] Yes, we provide warranties for most of our products, which vary in length depending on the item. You can find warranty details on each product page. </s>"},
    {"text": "<s>[INST] Can I return a product if I don't like it? [/INST] Yes, you can return most products within 30 days of purchase as long as they are in unused condition and with the original packaging. </s>"},
    {"text": "<s>[INST] Do you have repair services? [/INST] Yes, we offer repair services for various electronics, including smartphones and laptops. Please contact customer service for more details. </s>"},
    {"text": "<s>[INST] How do I track my order? [/INST] After your order ships, you will receive a tracking number via email. You can use that to track your order through the carrier’s website. </s>"},
    {"text": "<s>[INST] Can I pre-order new electronics? [/INST] Yes, we offer pre-orders for upcoming product releases. Check the product page for availability and expected release dates. </s>"},
    {"text": "<s>[INST] What payment methods do you accept? [/INST] We accept credit cards, PayPal, and various digital wallets. You can see all available payment options at checkout. </s>"},
    {"text": "<s>[INST] Do you have same-day delivery? [/INST] Yes, same-day delivery is available for select products in certain areas. Check the delivery options at checkout to see if your location qualifies. </s>"},
    {"text": "<s>[INST] Do you sell refurbished electronics? [/INST] Yes, we sell certified refurbished electronics with warranties. These are inspected, repaired, and tested to meet our quality standards. </s>"},
    {"text": "<s>[INST] Can I cancel my order? [/INST] You can cancel your order within 24 hours of placing it. After that, the order may have already shipped and cannot be canceled. </s>"},
    {"text": "<s>[INST] What is your return policy? [/INST] We accept returns within 30 days for most products. The items must be unused and in their original packaging. Some exclusions may apply. </s>"},
    {"text": "<s>[INST] Do you offer tech support? [/INST] Yes, we offer tech support for many of our products. You can reach our support team by phone or through our online chat system. </s>"},
    {"text": "<s>[INST] How do I set up my new TV? [/INST] Setting up your new TV is easy! You’ll find an instructional guide in the box. You can also watch our setup video on our website. </s>"},
    {"text": "<s>[INST] Do you offer gift cards? [/INST] Yes, we offer gift cards that you can purchase online or in-store. They are available in various denominations. </s>"},
    {"text": "<s>[INST] Can I get a student discount? [/INST] Yes, we offer student discounts on select items. You can verify your student status through our online verification portal. </s>"},
    {"text": "<s>[INST] What is the difference between a smart TV and a regular TV? [/INST] A smart TV can connect to the internet and run apps like Netflix, Hulu, and YouTube. Regular TVs only provide basic viewing options. </s>"},
    {"text": "<s>[INST] How do I update the software on my smartphone? [/INST] To update your smartphone, go to Settings, then tap 'Software Update.' You can follow the on-screen instructions to install the latest version. </s>"},
    {"text": "<s>[INST] What is your price match policy? [/INST] We will match a competitor’s price on an identical product, provided it’s in stock and meets our criteria. Contact customer service for more information. </s>"},
    {"text": "<s>[INST] Can I schedule a product delivery? [/INST] Yes, during checkout you can select a delivery date that works best for you, subject to availability. </s>"},
    {"text": "<s>[INST] Do you sell phone cases? [/INST] Yes, we offer a variety of phone cases for different models, including protective, stylish, and custom options. </s>"},
    {"text": "<s>[INST] How long does delivery take? [/INST] Delivery times vary depending on your location. Standard delivery usually takes 3-5 business days, but expedited options are available. </s>"},
    {"text": "<s>[INST] Do you offer free shipping? [/INST] Yes, we offer free shipping on orders over a certain amount. Please check the shipping details at checkout. </s>"},
    {"text": "<s>[INST] Can I get a discount on bulk purchases? [/INST] Yes, we offer discounts for bulk orders. Please contact our sales team for more details. </s>"},
    {"text": "<s>[INST] Do you offer financing options? [/INST] Yes, we offer financing through a third-party provider, allowing you to pay for your purchases in installments. </s>"},
    {"text": "<s>[INST] What is the return process for defective products? [/INST] If you receive a defective product, please contact us within 14 days for a return or exchange. We’ll guide you through the process. </s>"},
    {"text": "<s>[INST] Do you sell video game consoles? [/INST] Yes, we sell various video game consoles including PlayStation, Xbox, and Nintendo Switch. </s>"},
    {"text": "<s>[INST] Are your products authentic? [/INST] Yes, all of our products are 100% authentic and come directly from the manufacturer or authorized distributors. </s>"},
    {"text": "<s>[INST] Can I upgrade the RAM on my laptop? [/INST] Many of our laptops have upgradable RAM. Please check the product specifications or consult with our tech support team for compatibility. </s>"},
    {"text": "<s>[INST] Do you sell smart home devices? [/INST] Yes, we offer a variety of smart home devices including smart speakers, lights, thermostats, and security cameras. </s>"},
    {"text": "<s>[INST] How can I connect my new Bluetooth speaker? [/INST] To connect your Bluetooth speaker, simply turn it on, enable Bluetooth on your phone or device, and select the speaker from the list of available devices. </s>"},
    {"text": "<s>[INST] Can I install apps on my smart TV? [/INST] Yes, most smart TVs allow you to download and install apps directly from the TV’s app store. </s>"},
    {"text": "<s>[INST] Do you offer a price guarantee? [/INST] Yes, we guarantee the best prices on our products. If you find a lower price elsewhere, we’ll match it. </s>"},
    {"text": "<s>[INST] Can I upgrade the storage on my phone? [/INST] Some phones allow you to expand storage using an SD card, while others have fixed storage. Please check your phone's specifications for details. </s>"},
    {"text": "<s>[INST] What is your policy on damaged goods? [/INST] If you receive a damaged item, please contact us immediately with photos, and we will arrange for a return or replacement. </s>"},
    {"text": "<s>[INST] What is the difference between an LED and an OLED TV? [/INST] OLED TVs offer better picture quality with more vibrant colors and deeper blacks, whereas LED TVs use backlighting and are more affordable. </s>"},
    {"text": "<s>[INST] How do I set up my new wireless router? [/INST] To set up your router, follow the instructions in the manual, connect it to your modem, and follow the setup wizard on your computer or mobile device. </s>"},
    {"text": "<s>[INST] Do you sell phone chargers? [/INST] Yes, we offer a range of phone chargers, including fast chargers, wireless chargers, and portable power banks. </s>"},
    {"text": "<s>[INST] Can I transfer data from my old phone to my new one? [/INST] Yes, we offer data transfer services to help move your information from your old phone to your new one. </s>"},
    {"text": "<s>[INST] What is a smart thermostat? [/INST] A smart thermostat allows you to control your home’s temperature remotely using an app, helping you save energy and create customized schedules. </s>"},
    {"text": "<s>[INST] Can I install a security camera myself? [/INST] Yes, many of our security cameras are DIY-friendly and come with detailed instructions for easy installation. </s>"}
]
